[package]
name = "calyx"
version = "0.1.0"
authors = [
  "Samuel Thomas <sgt43@cornell.edu>",
  "Kenneth Fang <kwf37@cornell.edu>",
  "Zhijing Li <zl679@cornell.edu>",
  "Rachit Nigam <rnigam@cs.cornell.edu>",
  "Adrian Sampson <asampson@cs.cornell.edu>",
]
edition = "2018"
build = false
# build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]
structopt = "0.3.12"
petgraph = "0.5.0"
sexpy = "0.5.3"
itertools = "0.9.0"
bumpalo = "3.2.1"
atty = "0.2.14"
linefeed = "0.6.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.pretty]
version = "0.9.0"
features = ["termcolor"]

# [build-dependencies]
# clap = "2.33"
# structopt = "~0.3"
